name: "Pl3xMapGriefprevention"
main: "net.pl3xmap.map.vnp.Pl3xMapVanishNoPacket"
version: "1.0.0"
description: "Pl3xMapVanishNoPacket Pl3xMap support"
api-version: "1.16"
authors: [ BillyGalbreath, NeumimTo ]
depend:
  - VanishNoPacket
  - Pl3xMap
