name: "${project.name}"
main: "${project.groupId}.Pl3xMapWorldGuard"
version: "${project.version}"
description: "${project.description}"
api-version: "1.16"
authors: [ BillyGalbreath ]
softdepend:
  - WorldGuard
  - Pl3xMap
